micronaut.mcp.server.transport=STDIO
micronaut.mcp.server.info.name=mcp-selenium-server
micronaut.mcp.server.info.version=1.0.0
micronaut.mcp.server.reactive=true
micronaut.banner.enabled=false
micronaut.server.enabled=false
logging.level.io.micronaut=ERROR
logging.level.root=ERROR
