plugins {
    id 'java'
    id 'application'
    id 'io.micronaut.application' version '5.0.2'
    id 'com.gradleup.shadow' version '9.6.1'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'io.github.bonigarcia.ce.McpSeleniumServer'
}

micronaut {
    version = '4.10.11'
}

dependencies {
    implementation 'io.micronaut.mcp:micronaut-mcp-server-java-sdk'
    implementation 'io.micronaut:micronaut-jackson-databind'
    implementation 'org.seleniumhq.selenium:selenium-java:4.48.0'
    runtimeOnly 'ch.qos.logback:logback-classic'
}
