plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'io.github.bonigarcia.ce.McpSeleniumServer'
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

dependencies {
    implementation platform('io.modelcontextprotocol.sdk:mcp-bom:2.0.1')
    implementation 'io.modelcontextprotocol.sdk:mcp'
    implementation 'org.seleniumhq.selenium:selenium-java:4.48.0'
}
